### ISSUE TITLE
personal access token, using a self-hosted gitlab instance

### ISSUE THREAD

**Issue by diniremix** [thblckjkr/insomnia-plugin-gist-sync#1]
hello, very good plugin! 👍 

I have done the installation and I have noticed that in the documentation that you expose [configuration section](https://github.com/thblckjkr/insomnia-plugin-sync-gist-multiprovider#configure), you comment on the creation of a **personal access token**, however, in [snippets api docs](https://docs.gitlab.com/ce/api/snippets.html#snippets-api), they say that the personal access token should be sent as follows:

```sh
curl --header "PRIVATE-TOKEN: <your_access_token>" "https://gitlab.example.com/api/v4/snippets"
````
and not as a Bearer Token
```js
{ Authorization: `Bearer ${this.config.token}` },
```

I have made the change in the `authenticate` method and it works perfectly, I also increased the Axios response time because it generates timeout errors
 
**gitlab.js**
```js
authenticate() {
    return axios.create({
      baseURL: `${this.config.api_url}`,
      timeout: 30000,
      headers: { 'private-token': `${this.config.token}` },
    });
  }
```

we are using a self-hosted gitlab instance, GitLab CE (12.0.3) 😄 

again, thank you very much and sorry for the bad translation, I don't speak English 😰

**Comment by thblckjkr** [comment]
Hi @diniremix! Thanks for the feedback.

We are using a self-hosted gitlab (v13.0.9) instance too, and we haven't had any issues with it. We also tested it before on a 12.0.x instance and we did not had any problems with it.

While it is true that the snippets authentication says that the authentication must be done with the `PRIVATE-TOKEN` parameter, when you go to see the [api authentication](https://docs.gitlab.com/ee/api/README.html#personalproject-access-tokens) section, there is a note that states:

> You can also use personal/project access tokens with OAuth-compliant headers

Since OAuth is a more *standard* way to do the authentication, I wanted to keep it that way. I didn't think it would cause problems. If you want to make a pull-request fixing the problem, you are welcome.

PD. I think the problem was the timeout, and not the header name. I will make the timeout a optional configuration parameter too.

----

¡Hola! Gracias por tu feedback.

En nuestro caso también estamos utilizando una instancia self-hosted de giltab (v13.0.9), y no hemos tenido ningún problema con la sincronización. También lo probamos hace tiempo en una instancia de la versión 12.0.x y no tuvimos problemas.

Si bien, es cierto que la documentación de los snippets dice que la autenticación tiene que realizarse con el parámetro `PRIVATE-TOKEN`, cuando ves la sección de [autenticación general del api](https://docs.gitlab.com/ee/api/README.html#personalproject-access-tokens) dice que si bien es cierto que se tiene que utilizar, también es posible usar "headers de acuerdo al estándar OAuth".

Decidí dejarlo con el método de autenticación Bearer porque es estándar, pero no creí que fuera a dar problemas con la autenticación. Si deseas hacer un pull-request con los fixes, eres bienvenido.

PD. Creo que el problema era el timeout, no el nombre del header. Creo que haré el timeout un parámetro opcional de la configuración.
